name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  macos_tests:
    runs-on: macos-12
    strategy:
      matrix:
        xcode:
          - "14.2" # Swift 5.7.2
        command:
          - test
          # - benchmarks
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: System
        run: system_profiler SPHardwareDataType
      - name: Run ${{ matrix.command }}
        run: make ${{ matrix.command }}

  ubuntu_tests:
    name: Ubuntu (Swift ${{ matrix.swift }})
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        swift:
          - '5.9'
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - run: swift test
